import sqlite3
con = sqlite3.connect("map.db")
cur = con.cursor()

regions = [
"beyound the wall"   ,
"castle black" ,
"bay of seals" ,
"bay of ice" ,
"winterfell" ,
"karhold" ,
"the dreadfort" ,
"stony shore" ,
"north sunset sea" ,
"barrowhands" ,
"moat calin" ,
"white harbor" ,
"the shivering sea" ,
"the neck" ,
"deepwood motte" ,
"flint's finger" ,
"blazewater bay" ,
"the twins" ,
"the fingers" ,
"the bite" ,
"north narrow sea" ,
"the eyrie" ,
"ironmans's bay" ,
"kings road" ,
"riverlands" ,
"montains of the moon" ,
"bay of crabs" ,
"braavos" ,
"braavos sea" ,
"crackclaw point" ,
"harrenhal" ,
"riverrun" ,
"casterly rock" ,
"great wyk" ,
"harlaw" ,
"pyke" ,
"the golden sound" ,
"westerlands" ,
"stony sept" ,
"crownland" ,
"blackwater bay" ,
"dragonstone" ,
"the narrow sea" ,
"pentos" ,
"king's wood" ,
"king's landing" ,
"blackwater rush" ,
"the reach" ,
"lannisport" ,
"searoad" ,
"south sunset sea" ,
"shield islands" ,
"stromlands" ,
"strom's end" ,
"shipbreaker bay" ,
"sea of myrth" ,
"myr" ,
"tyrosh" ,
"the disputed lands" ,
"step stones" ,
"griffin's roost" ,
"dornish marches" ,
"ashford" ,
"highgarden" ,
"horn hill" ,
"blackmont" ,
"prince's pass" ,
"sea of dorne" ,
"sunspear" ,
"godsgrace" ,
"hornwood" ,
"salt shore" ,
"sandstone" ,
"starfall" ,
"oldtown" ,
"redwynne straits" ,
"the arbor" ,
"west summer sea",
"east summer sea" ,
"nom"


]

for region in regions:
    cur.execute("""INSERT INTO adjacence
    VALUES
    ("""+'"'+region+'"'+", 0" *79 + ");")
con.commit()
